name = "Newb Reimagined §bOptimized§r"
version = [0, 15, 7]
min_supported_mc_version = [1, 21, 20]
description = '''
§7A shader with a fantasy theme without losing the vanilla minecraft feel
%v | §c%w
§3https://sites.google.com/view/newb-reimagined/
''' # %w = patch warning, %v = version
authors = ["alyowv", "devendrn"]
url = "https://sites.google.com/view/newb-reimagined/"
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "LegacyCubemap", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
text = " Recommeded:\n§7 Set brightness to 10 - 30\n Don't use texture packs to avoid some bugs\n Restart your minecraft after enabling this shader§r" 

[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default


[[subpack]]
define = "LOW"
materials = ["RenderChunk", "Clouds"]
description = '''
§l§2Low\n§r§7Vanilla Clouds, No Aurora, No Wave, No Glow Leak, No Fog
'''

[[subpack]]
define = "LITE"
materials = ["RenderChunk", "Clouds"]
description = '''
§l§aLite\n§r§7Vanilla Clouds, No Aurora, No Wave, No Glow Leak
'''

[[subpack]]
define = "MEDIUM"
materials = ["RenderChunk", "Clouds"]
description = '''
§l§6Medium\n§r§7Soft Clouds, No Aurora, No Wave, No Glow Leak
'''

[[subpack]]
define = "CDEF"
materials = []
description = '''
§lDefault\n§r§7Rounded Clouds, No Aurora, No Wave, No Glow Leak
'''
