name = "Newb Reimagined"
version = [0, 15, 68]
min_supported_mc_version = [1, 21, 20]
description = '''
§7A shader with a fantasy theme without losing the vanilla minecraft feel
%v | §c%w
§3https://sites.google.com/view/newb-reimagined/
''' # %w = patch warning, %v = version
authors = ["alyowv", "devendrn"]
url = "https://sites.google.com/view/newb-reimagined/"
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "LegacyCubemap", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
text = " Recommeded:\n§7 Set brightness to 10 - 30\n Don't use texture packs to avoid some bugs\n Restart your minecraft after enabling this shader§r" 

[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds"]
description = '''
§lVanilla Clouds\n§r§7No Aurora
'''

[[subpack]]
define = "SOFT_CLOUDS"
materials = ["RenderChunk", "Clouds"]
description = '''
§lSoft Clouds\n§r§7Cirrus Clouds Style, No Aurora
'''

[[subpack]]
define = "DOUBLE_CLOUDS"
materials = ["Clouds"]
description = '''
§lDouble Cloud Layers\n§r§7Two Cloud Layers, No Aurora
'''

[[subpack]]
define = "ENDSKY1"
materials = ["RenderChunk", "EndSky"]
description = '''
§lEnd Sky 1\n§r§7 End Sky Type 1
'''

[[subpack]]
define = "ALWAYS_REFL"
materials = ["RenderChunk", "Sky"]
description = '''
§lAlways Reflection\n§r§7Ground Reflection, Aurora Reflection
'''

[[subpack]]
define = "AURORA2"
materials = ["RenderChunk", "Clouds"]
description = '''
§lAurora\n§r§7Aurora §bLight Blue §aGreen§r
'''

[[subpack]]
define = "AURORA1"
materials = ["RenderChunk", "Clouds"]
description = '''
§lAurora\n§r§7Aurora §bLight Blue §uPurple§r
'''

[[subpack]]
define = "COMP"
materials = []
description = '''
§lDefault\n§r§7Rounded Clouds, No Aurora
'''
